import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import Nav from "@/components/navbar/Nav";
import Provider from "./Provider";
import { ClerkProvider } from "@clerk/nextjs";

const kanit = Kanit({
  weight: ['400', '600'],
  subsets: ['latin', 'thai']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${kanit.className} antialiased`}
        >
          <Provider>
            <Nav />
            <main className="container">
              {children}
            </main>
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
